### ISSUE TITLE
TITaiko cannot read data

### ISSUE THREAD

**Issue by SixBeeps** [SixBeeps/TIRhythm#5]
Getting the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "TITaiko.py", line 30, in <module>
IndexError: list index out of range
```

**Comment by SixBeeps** [comment]
I believe this is related to #4 but I'm not entirely sure yet.

**Comment by SixBeeps** [comment]
This was apparently due to a loading issue in the Nspire Student Software, and a reboot fixed the issue.
